// <auto-generated />
using System;
using Asp.MVC.Learning.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Asp.MVC.Learning.Migrations
{
    [DbContext(typeof(testDatabase))]
    partial class testDatabaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Asp.MVC.Learning.Models.Test", b =>
                {
                    b.Property<int>("TestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TestId");

                    b.ToTable("tests");
                });

            modelBuilder.Entity("NetCoreFastenalLib.DataModels.AdditonalProperty", b =>
                {
                    b.Property<int>("PropertyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("MroPartPartId")
                        .HasColumnType("int");

                    b.Property<string>("PropertyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PropertyValue")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PropertyId");

                    b.HasIndex("MroPartPartId");

                    b.ToTable("AdditonalProperty");
                });

            modelBuilder.Entity("NetCoreFastenalLib.DataModels.Address", b =>
                {
                    b.Property<int>("addressID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("District")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("addressID");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("NetCoreFastenalLib.DataModels.CellphoneNumber", b =>
                {
                    b.Property<int>("TelephoneID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(11)")
                        .HasMaxLength(11);

                    b.HasKey("TelephoneID");

                    b.ToTable("CellphoneNumber");
                });

            modelBuilder.Entity("NetCoreFastenalLib.DataModels.ContactPerson", b =>
                {
                    b.Property<int>("PeronID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<short>("Age")
                        .HasColumnType("smallint");

                    b.Property<int?>("CellphoneNumberTelephoneID")
                        .HasColumnType("int");

                    b.Property<string>("EmailAdress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SupplierBaseSupplierID")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WiredPhoneNumberTelephoneID")
                        .HasColumnType("int");

                    b.HasKey("PeronID");

                    b.HasIndex("CellphoneNumberTelephoneID");

                    b.HasIndex("SupplierBaseSupplierID");

                    b.HasIndex("WiredPhoneNumberTelephoneID");

                    b.ToTable("ContactPerson");
                });

            modelBuilder.Entity("NetCoreFastenalLib.DataModels.DohItems", b =>
                {
                    b.Property<int>("DohItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AnnualUsage")
                        .HasColumnType("int");

                    b.Property<float>("AverageVPOPurchaseCost")
                        .HasColumnType("real");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CurrencyType")
                        .HasColumnType("int");

                    b.Property<int>("CurrentQOH")
                        .HasColumnType("int");

                    b.Property<int?>("FastenalCodeId")
                        .HasColumnType("int");

                    b.Property<string>("IsAgreementCoversAllInventoryPurchase")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MyBranchCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OneApprovalID")
                        .HasColumnType("int");

                    b.Property<int>("OrderFrequency")
                        .HasColumnType("int");

                    b.Property<int>("OrderQty")
                        .HasColumnType("int");

                    b.Property<string>("OtherCommentAboutCommitmentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("PurchaseCost")
                        .HasColumnType("real");

                    b.Property<int>("QtyOfOpenPo")
                        .HasColumnType("int");

                    b.Property<int>("QtyOfReceive")
                        .HasColumnType("int");

                    b.Property<int>("QtyOfStock")
                        .HasColumnType("int");

                    b.Property<int>("ReleaseNumber")
                        .HasColumnType("int");

                    b.Property<int>("SafetyLeadtime")
                        .HasColumnType("int");

                    b.Property<float>("SellingPrice")
                        .HasColumnType("real");

                    b.Property<int>("SrPoTrackingQty")
                        .HasColumnType("int");

                    b.Property<string>("TypeOfInventoryCommitment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VPONumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fastenalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fastenalDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vendorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("vendorLeadtime")
                        .HasColumnType("int");

                    b.Property<int>("vendorMoq")
                        .HasColumnType("int");

                    b.Property<string>("vendorName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DohItemId");

                    b.HasIndex("FastenalCodeId");

                    b.HasIndex("OneApprovalID");

                    b.ToTable("DohItems");
                });

            modelBuilder.Entity("NetCoreFastenalLib.DataModels.DohSimplified", b =>
                {
                    b.Property<int>("DohSimplifiedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FastenalCode")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<int>("LeadTime")
                        .HasColumnType("int");

                    b.Property<int>("PMU")
                        .HasColumnType("int");

                    b.HasKey("DohSimplifiedId");

                    b.ToTable("DohSimplifieds");
                });

            modelBuilder.Entity("NetCoreFastenalLib.DataModels.Employee", b =>
                {
                    b.Property<int>("PeronID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<short>("Age")
                        .HasColumnType("smallint");

                    b.Property<int?>("CellphoneNumberTelephoneID")
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WiredPhoneNumberTelephoneID")
                        .HasColumnType("int");

                    b.HasKey("PeronID");

                    b.HasIndex("CellphoneNumberTelephoneID");

                    b.HasIndex("WiredPhoneNumberTelephoneID");

                    b.ToTable("Employees");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Employee");
                });

            modelBuilder.Entity("NetCoreFastenalLib.DataModels.FastenalBranch", b =>
                {
                    b.Property<int>("FastenalBranchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BranchCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BranchName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FastenalBranchId");

                    b.ToTable("FastenalBranches");
                });

            modelBuilder.Entity("NetCoreFastenalLib.DataModels.FastenalCode", b =>
                {
                    b.Property<int>("FastenalCodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FastenalDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FastenalPartNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FastenalCodeId");

                    b.ToTable("FastenalPartCodesFTS");

                    b.HasDiscriminator<string>("Discriminator").HasValue("FastenalCode");
                });

            modelBuilder.Entity("NetCoreFastenalLib.DataModels.FastenalCodeAverageVPOAndSellPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("AverageSellPrice")
                        .HasColumnType("float");

                    b.Property<double>("AverageVPOPrice")
                        .HasColumnType("float");

                    b.Property<string>("FastenalPartNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FastenalCodeAverageVPOAndSellPrices");
                });

            modelBuilder.Entity("NetCoreFastenalLib.DataModels.FastenalCodeForecastFromCustomer", b =>
                {
                    b.Property<int>("ForccastId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FastenalPartNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ForecastQty")
                        .HasColumnType("int");

                    b.HasKey("ForccastId");

                    b.ToTable("FastenalCodeForecastFromCustomers");
                });

            modelBuilder.Entity("NetCoreFastenalLib.DataModels.FastenalCodeLeadTime", b =>
                {
                    b.Property<int>("FastenalCodeLeadTimeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FastenalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("LeadTime")
                        .HasColumnType("real");

                    b.Property<int>("OrderFrequency")
                        .HasColumnType("int");

                    b.Property<int>("SafetyLeadTime")
                        .HasColumnType("int");

                    b.HasKey("FastenalCodeLeadTimeId");

                    b.ToTable("FastenalCodeLeadtimes");
                });

            modelBuilder.Entity("NetCoreFastenalLib.DataModels.FastenalCodeMOQ", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FastenalPartNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Moq")
                        .HasColumnType("int");

                    b.Property<int?>("VendorId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("VendorId");

                    b.ToTable("FastenalCodeMOQs");
                });

            modelBuilder.Entity("NetCoreFastenalLib.DataModels.FastenalCodeMinMax", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FastenalPartNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ForecastQty")
                        .HasColumnType("int");

                    b.Property<bool>("IsHubControl")
                        .HasColumnType("bit");

                    b.Property<int>("OrderFrequency")
                        .HasColumnType("int");

                    b.Property<int>("TotalHalfYearUsage")
                        .HasColumnType("int");

                    b.Property<int>("UsageMonth01")
                        .HasColumnType("int");

                    b.Property<int>("UsageMonth02")
                        .HasColumnType("int");

                    b.Property<int>("UsageMonth03")
                        .HasColumnType("int");

                    b.Property<int>("UsageMonth04")
                        .HasColumnType("int");

                    b.Property<int>("UsageMonth05")
                        .HasColumnType("int");

                    b.Property<int>("UsageMonth06")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("FastenalCodeMinMaxes");
                });

            modelBuilder.Entity("NetCoreFastenalLib.DataModels.FastenalCodeSixMonthUsage", b =>
                {
                    b.Property<int>("FastenalUsageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FastenalPartNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderFrequency")
                        .HasColumnType("int");

                    b.Property<int>("TotalHalfYearUsage")
                        .HasColumnType("int");

                    b.Property<int>("UsageMonth01")
                        .HasColumnType("int");

                    b.Property<int>("UsageMonth02")
                        .HasColumnType("int");

                    b.Property<int>("UsageMonth03")
                        .HasColumnType("int");

                    b.Property<int>("UsageMonth04")
                        .HasColumnType("int");

                    b.Property<int>("UsageMonth05")
                        .HasColumnType("int");

                    b.Property<int>("UsageMonth06")
                        .HasColumnType("int");

                    b.HasKey("FastenalUsageId");

                    b.ToTable("FastenalCodeSixMonthUsages");
                });

            modelBuilder.Entity("NetCoreFastenalLib.DataModels.ItemProperty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PropertyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("quotationItemItemId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("quotationItemItemId");

                    b.ToTable("ItemProperty");
                });

            modelBuilder.Entity("NetCoreFastenalLib.DataModels.MOQList", b =>
                {
                    b.Property<int>("MOQListID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FastenalPartNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReorderQty")
                        .HasColumnType("int");

                    b.Property<string>("VendorNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MOQListID");

                    b.ToTable("MOQList");
                });

            modelBuilder.Entity("NetCoreFastenalLib.DataModels.MroPart", b =>
                {
                    b.Property<int>("PartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CurrencyType")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FastenalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstLevelCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<double>("MOQ")
                        .HasColumnType("float");

                    b.Property<string>("PartName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PricePerSaleUnitWithoutVAT")
                        .HasColumnType("float");

                    b.Property<string>("SaleUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupplierBrandName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupplierModelInformation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupplierProductCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("SupplierSuggestedSalePrice")
                        .HasColumnType("float");

                    b.HasKey("PartId");

                    b.ToTable("MroParts");
                });

            modelBuilder.Entity("NetCoreFastenalLib.DataModels.OneApproval", b =>
                {
                    b.Property<int>("OneApprovalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FastenalBranchId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.Property<string>("WorksheetSavePath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OneApprovalID");

                    b.HasIndex("FastenalBranchId");

                    b.ToTable("Approvals");
                });

            modelBuilder.Entity("NetCoreFastenalLib.DataModels.PackagingType", b =>
                {
                    b.Property<int>("PackagingTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("MroPartPartId")
                        .HasColumnType("int");

                    b.Property<string>("PackagingTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QtyPerPackage")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PackagingTypeId");

                    b.HasIndex("MroPartPartId");

                    b.ToTable("PackagingType");
                });

            modelBuilder.Entity("NetCoreFastenalLib.DataModels.QuotationForSingleItem", b =>
                {
                    b.Property<int>("QuotationItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CommentsForThisQuotation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("MOQ")
                        .HasColumnType("float");

                    b.Property<string>("QuotationItemItemId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("QuotationState")
                        .HasColumnType("int");

                    b.Property<int?>("RFQSupplierSupplierID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReceivedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SentOutDate")
                        .HasColumnType("datetime2");

                    b.Property<float>("TargetPrice")
                        .HasColumnType("real");

                    b.Property<int>("ToolingFee")
                        .HasColumnType("int");

                    b.Property<float>("VatExcludedPrice")
                        .HasColumnType("real");

                    b.HasKey("QuotationItemId");

                    b.HasIndex("QuotationItemItemId");

                    b.HasIndex("RFQSupplierSupplierID");

                    b.ToTable("QuotationForSingleItems");
                });

            modelBuilder.Entity("NetCoreFastenalLib.DataModels.QuotationItem", b =>
                {
                    b.Property<string>("ItemId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CustomerDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("EAUFromCustomer")
                        .HasColumnType("float");

                    b.Property<int?>("QuotationProjectProjectId")
                        .HasColumnType("int");

                    b.Property<int>("quotationState")
                        .HasColumnType("int");

                    b.HasKey("ItemId");

                    b.HasIndex("QuotationProjectProjectId");

                    b.ToTable("QuotationItems");
                });

            modelBuilder.Entity("NetCoreFastenalLib.DataModels.QuotationProject", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("ActualEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpectedEndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectSerialID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SalesPersonPeronID")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("projectState")
                        .HasColumnType("int");

                    b.HasKey("ProjectId");

                    b.HasIndex("SalesPersonPeronID");

                    b.ToTable("QuotationProjects");
                });

            modelBuilder.Entity("NetCoreFastenalLib.DataModels.Quoter", b =>
                {
                    b.Property<int>("PeronID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<short>("Age")
                        .HasColumnType("smallint");

                    b.Property<int?>("CellphoneNumberTelephoneID")
                        .HasColumnType("int");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("QuotationProjectProjectId")
                        .HasColumnType("int");

                    b.Property<string>("QuoterName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WiredPhoneNumberTelephoneID")
                        .HasColumnType("int");

                    b.HasKey("PeronID");

                    b.HasIndex("CellphoneNumberTelephoneID");

                    b.HasIndex("QuotationProjectProjectId");

                    b.HasIndex("WiredPhoneNumberTelephoneID");

                    b.ToTable("Quoters");
                });

            modelBuilder.Entity("NetCoreFastenalLib.DataModels.SupplierBase", b =>
                {
                    b.Property<int>("SupplierID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("QuotationProjectProjectId")
                        .HasColumnType("int");

                    b.Property<int?>("SupplierAddressaddressID")
                        .HasColumnType("int");

                    b.Property<string>("SupplierBriefIntroduction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupplierChineseName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupplierEnglishName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SupplierID");

                    b.HasIndex("QuotationProjectProjectId");

                    b.HasIndex("SupplierAddressaddressID");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("NetCoreFastenalLib.DataModels.SupplierProduct", b =>
                {
                    b.Property<int>("SupplierProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ImageData")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ProductDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SupplierID")
                        .HasColumnType("int");

                    b.HasKey("SupplierProductId");

                    b.HasIndex("SupplierID");

                    b.ToTable("SupplierProduct");
                });

            modelBuilder.Entity("NetCoreFastenalLib.DataModels.SystemSetting", b =>
                {
                    b.Property<int>("SystemSettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InfoMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastForecastFolderPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastRunTimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUsedFolderPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MinMaxUsageLast6MonthHeaders")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SystemSettingId");

                    b.ToTable("SystemSettings");
                });

            modelBuilder.Entity("NetCoreFastenalLib.DataModels.UserInformation", b =>
                {
                    b.Property<int>("UserInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BranchFastenalBranchId")
                        .HasColumnType("int");

                    b.HasKey("UserInfoId");

                    b.HasIndex("BranchFastenalBranchId");

                    b.ToTable("UserInformation");
                });

            modelBuilder.Entity("NetCoreFastenalLib.DataModels.VendorForPO", b =>
                {
                    b.Property<int>("VendorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("VendorFastenalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VendorName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VendorId");

                    b.ToTable("VendorForPO");
                });

            modelBuilder.Entity("NetCoreFastenalLib.DataModels.WiredPhoneNumber", b =>
                {
                    b.Property<int>("TelephoneID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AreaCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(5)")
                        .HasMaxLength(5);

                    b.Property<string>("ExtensionNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.HasKey("TelephoneID");

                    b.ToTable("WiredPhoneNumber");
                });

            modelBuilder.Entity("NetCoreFastenalLib.ItemTreeCode", b =>
                {
                    b.Property<int>("ItemTreeCodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FastenalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<double>("MaterialCost")
                        .HasColumnType("float");

                    b.Property<double>("PosCost")
                        .HasColumnType("float");

                    b.Property<string>("StockType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VendorItemNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VendorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("ItemTreeCodeId");

                    b.ToTable("ItemTreeCodes");
                });

            modelBuilder.Entity("NetCoreFastenalLib.VPOItemCost", b =>
                {
                    b.Property<int>("VpoItemCostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BranchId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CurrencyType")
                        .HasColumnType("int");

                    b.Property<double>("ExchangeRateToUSD")
                        .HasColumnType("float");

                    b.Property<string>("FastenalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderQty")
                        .HasColumnType("int");

                    b.Property<double>("PriceInOriginalCurrency")
                        .HasColumnType("float");

                    b.Property<double?>("TotalAmountInOriginalCurrency")
                        .HasColumnType("float");

                    b.Property<string>("VendorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VendorNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VendorPO")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VpoItemCostId");

                    b.ToTable("VPOItems");
                });

            modelBuilder.Entity("NetCoreFastenalLib.DataModels.SalesPerson", b =>
                {
                    b.HasBaseType("NetCoreFastenalLib.DataModels.Employee");

                    b.HasDiscriminator().HasValue("SalesPerson");
                });

            modelBuilder.Entity("NetCoreFastenalLib.DataModels.FastenalCodeForOpenPO", b =>
                {
                    b.HasBaseType("NetCoreFastenalLib.DataModels.FastenalCode");

                    b.Property<DateTime>("DataLastUpdatedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OpenQty")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderQty")
                        .HasColumnType("int");

                    b.Property<string>("ProcessPartNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QtyReceived")
                        .HasColumnType("int");

                    b.Property<int?>("VendorId")
                        .HasColumnType("int");

                    b.Property<string>("VendorPartNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VendorPoNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("VendorId");

                    b.ToTable("FastenalPartCodesFTS");

                    b.HasDiscriminator().HasValue("FastenalCodeForOpenPO");
                });

            modelBuilder.Entity("NetCoreFastenalLib.DataModels.FastenalCodeForStock", b =>
                {
                    b.HasBaseType("NetCoreFastenalLib.DataModels.FastenalCode");

                    b.Property<int>("QOH")
                        .HasColumnType("int");

                    b.Property<string>("StorageLocation")
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.ToTable("FastenalPartCodesFTS");

                    b.HasDiscriminator().HasValue("FastenalCodeForStock");
                });

            modelBuilder.Entity("NetCoreFastenalLib.DataModels.FastenalCodeInReceiveExcelFile", b =>
                {
                    b.HasBaseType("NetCoreFastenalLib.DataModels.FastenalCode");

                    b.Property<string>("CarrierType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataLastUpdatedTime")
                        .HasColumnName("FastenalCodeInReceiveExcelFile_DataLastUpdatedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastScannedInDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OriginalBranch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.ToTable("FastenalPartCodesFTS");

                    b.HasDiscriminator().HasValue("FastenalCodeInReceiveExcelFile");
                });

            modelBuilder.Entity("NetCoreFastenalLib.DataModels.AdditonalProperty", b =>
                {
                    b.HasOne("NetCoreFastenalLib.DataModels.MroPart", null)
                        .WithMany("additonalProperties")
                        .HasForeignKey("MroPartPartId");
                });

            modelBuilder.Entity("NetCoreFastenalLib.DataModels.ContactPerson", b =>
                {
                    b.HasOne("NetCoreFastenalLib.DataModels.CellphoneNumber", "CellphoneNumber")
                        .WithMany()
                        .HasForeignKey("CellphoneNumberTelephoneID");

                    b.HasOne("NetCoreFastenalLib.DataModels.SupplierBase", null)
                        .WithMany("Contacts")
                        .HasForeignKey("SupplierBaseSupplierID");

                    b.HasOne("NetCoreFastenalLib.DataModels.WiredPhoneNumber", "WiredPhoneNumber")
                        .WithMany()
                        .HasForeignKey("WiredPhoneNumberTelephoneID");
                });

            modelBuilder.Entity("NetCoreFastenalLib.DataModels.DohItems", b =>
                {
                    b.HasOne("NetCoreFastenalLib.DataModels.FastenalCode", null)
                        .WithMany("DohItems")
                        .HasForeignKey("FastenalCodeId");

                    b.HasOne("NetCoreFastenalLib.DataModels.OneApproval", "oneApproval")
                        .WithMany("dohItems")
                        .HasForeignKey("OneApprovalID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NetCoreFastenalLib.DataModels.Employee", b =>
                {
                    b.HasOne("NetCoreFastenalLib.DataModels.CellphoneNumber", "CellphoneNumber")
                        .WithMany()
                        .HasForeignKey("CellphoneNumberTelephoneID");

                    b.HasOne("NetCoreFastenalLib.DataModels.WiredPhoneNumber", "WiredPhoneNumber")
                        .WithMany()
                        .HasForeignKey("WiredPhoneNumberTelephoneID");
                });

            modelBuilder.Entity("NetCoreFastenalLib.DataModels.FastenalCodeMOQ", b =>
                {
                    b.HasOne("NetCoreFastenalLib.DataModels.VendorForPO", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorId");
                });

            modelBuilder.Entity("NetCoreFastenalLib.DataModels.ItemProperty", b =>
                {
                    b.HasOne("NetCoreFastenalLib.DataModels.QuotationItem", "quotationItem")
                        .WithMany("ItemProperties")
                        .HasForeignKey("quotationItemItemId");
                });

            modelBuilder.Entity("NetCoreFastenalLib.DataModels.OneApproval", b =>
                {
                    b.HasOne("NetCoreFastenalLib.DataModels.FastenalBranch", "Branch")
                        .WithMany("ApprovalsApplied")
                        .HasForeignKey("FastenalBranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NetCoreFastenalLib.DataModels.PackagingType", b =>
                {
                    b.HasOne("NetCoreFastenalLib.DataModels.MroPart", null)
                        .WithMany("Packages")
                        .HasForeignKey("MroPartPartId");
                });

            modelBuilder.Entity("NetCoreFastenalLib.DataModels.QuotationForSingleItem", b =>
                {
                    b.HasOne("NetCoreFastenalLib.DataModels.QuotationItem", "QuotationItem")
                        .WithMany()
                        .HasForeignKey("QuotationItemItemId");

                    b.HasOne("NetCoreFastenalLib.DataModels.SupplierBase", "RFQSupplier")
                        .WithMany()
                        .HasForeignKey("RFQSupplierSupplierID");
                });

            modelBuilder.Entity("NetCoreFastenalLib.DataModels.QuotationItem", b =>
                {
                    b.HasOne("NetCoreFastenalLib.DataModels.QuotationProject", null)
                        .WithMany("QuotationItems")
                        .HasForeignKey("QuotationProjectProjectId");
                });

            modelBuilder.Entity("NetCoreFastenalLib.DataModels.QuotationProject", b =>
                {
                    b.HasOne("NetCoreFastenalLib.DataModels.SalesPerson", null)
                        .WithMany("ProjectsTakenCareOf")
                        .HasForeignKey("SalesPersonPeronID");
                });

            modelBuilder.Entity("NetCoreFastenalLib.DataModels.Quoter", b =>
                {
                    b.HasOne("NetCoreFastenalLib.DataModels.CellphoneNumber", "CellphoneNumber")
                        .WithMany()
                        .HasForeignKey("CellphoneNumberTelephoneID");

                    b.HasOne("NetCoreFastenalLib.DataModels.QuotationProject", null)
                        .WithMany("AssignedQuoters")
                        .HasForeignKey("QuotationProjectProjectId");

                    b.HasOne("NetCoreFastenalLib.DataModels.WiredPhoneNumber", "WiredPhoneNumber")
                        .WithMany()
                        .HasForeignKey("WiredPhoneNumberTelephoneID");
                });

            modelBuilder.Entity("NetCoreFastenalLib.DataModels.SupplierBase", b =>
                {
                    b.HasOne("NetCoreFastenalLib.DataModels.QuotationProject", null)
                        .WithMany("Suppliers")
                        .HasForeignKey("QuotationProjectProjectId");

                    b.HasOne("NetCoreFastenalLib.DataModels.Address", "SupplierAddress")
                        .WithMany()
                        .HasForeignKey("SupplierAddressaddressID");
                });

            modelBuilder.Entity("NetCoreFastenalLib.DataModels.SupplierProduct", b =>
                {
                    b.HasOne("NetCoreFastenalLib.DataModels.SupplierBase", "supplier")
                        .WithMany("Products")
                        .HasForeignKey("SupplierID");
                });

            modelBuilder.Entity("NetCoreFastenalLib.DataModels.UserInformation", b =>
                {
                    b.HasOne("NetCoreFastenalLib.DataModels.FastenalBranch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchFastenalBranchId");
                });

            modelBuilder.Entity("NetCoreFastenalLib.DataModels.FastenalCodeForOpenPO", b =>
                {
                    b.HasOne("NetCoreFastenalLib.DataModels.VendorForPO", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorId");
                });
#pragma warning restore 612, 618
        }
    }
}
